spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.ca8qpjan8tx2.ap-northeast-2.rds.amazonaws.com:3306/DB?serverTimezone=UTC&characterEncoding=UTF-8
    username: project
    password: project

jpa:
  properties:
    hibernate:
      show_sql: true
      format_sql: true
      naming:
        PhysicalNamingStrategyStandardImpl: true

logging:
  level:
    com.tutorial: debug

jwt:
  secret:
